import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Home
        </Link>

        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">
          Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
        </p>

        <div className="prose prose-gray max-w-none">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using ESGTracker (&ldquo;Service&rdquo;), you agree to be bound by
            these Terms of Service. If you do not agree to these terms, please
            do not use our Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            ESGTracker provides AI-generated Environmental, Social, and
            Governance (ESG) reports for informational purposes. Our reports are
            designed to help businesses understand and communicate their ESG
            practices.
          </p>

          <h2>3. Important Disclaimers</h2>
          <p>
            <strong>
              THE REPORTS GENERATED BY ESGTRACKER ARE FOR INFORMATIONAL PURPOSES
              ONLY AND DO NOT CONSTITUTE:
            </strong>
          </p>
          <ul>
            <li>Legal advice or legal opinions</li>
            <li>Financial advice or investment recommendations</li>
            <li>Official regulatory compliance certification</li>
            <li>Audited or verified environmental data</li>
            <li>Professional consulting services</li>
          </ul>
          <p>
            You should always consult with qualified legal, financial, and
            environmental professionals before making compliance decisions or
            submitting reports to regulatory bodies.
          </p>

          <h2>4. User Responsibilities</h2>
          <p>You are responsible for:</p>
          <ul>
            <li>Providing accurate information when generating reports</li>
            <li>Verifying the accuracy of generated content</li>
            <li>Maintaining the confidentiality of your account</li>
            <li>Complying with all applicable laws and regulations</li>
            <li>Not using the Service for fraudulent purposes</li>
          </ul>

          <h2>5. Subscription and Billing</h2>
          <p>
            Paid subscriptions are billed in advance on a monthly or annual
            basis. You may cancel your subscription at any time, and
            cancellation will take effect at the end of the current billing
            period.
          </p>
          <p>
            We offer a 14-day money-back guarantee for new subscriptions. Refund
            requests must be submitted within 14 days of the initial purchase.
          </p>

          <h2>6. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, ESGTRACKER AND ITS
            AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
            SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS
            OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY.
          </p>
          <p>
            Our total liability for any claims arising from your use of the
            Service shall not exceed the amount you paid us in the 12 months
            preceding the claim.
          </p>

          <h2>7. Intellectual Property</h2>
          <p>
            You retain ownership of any data you provide to generate reports.
            Reports generated using our Service may be used for your business
            purposes. ESGTracker retains ownership of the Service, including all
            software, algorithms, and methodologies.
          </p>

          <h2>8. Data Privacy</h2>
          <p>
            Your use of the Service is also governed by our Privacy Policy.
            Please review our Privacy Policy to understand how we collect, use,
            and protect your information.
          </p>

          <h2>9. Modifications to Terms</h2>
          <p>
            We may modify these Terms at any time. We will notify users of
            material changes via email or through the Service. Continued use of
            the Service after modifications constitutes acceptance of the
            updated Terms.
          </p>

          <h2>10. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of the State of Delaware, United States, without regard to
            its conflict of law provisions.
          </p>

          <h2>11. Contact Information</h2>
          <p>
            For questions about these Terms, please contact us at:
            <br />
            Email: legal@esgtracker.io
          </p>
        </div>
      </div>
    </div>
  );
}
