import Link from "next/link";
import { ArrowLeft, AlertTriangle } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <Link
          href="/"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-8"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Home
        </Link>

        <h1 className="text-3xl font-bold mb-8">Legal Disclaimer</h1>

        <Card className="mb-8 border-yellow-200 bg-yellow-50">
          <CardContent className="pt-6">
            <div className="flex gap-4">
              <AlertTriangle className="h-6 w-6 text-yellow-600 shrink-0" />
              <div>
                <h2 className="font-semibold text-yellow-800 mb-2">
                  Important Notice
                </h2>
                <p className="text-yellow-700">
                  ESGTracker reports are AI-generated and intended for
                  informational and internal planning purposes only. They should
                  not be relied upon as the sole basis for compliance decisions.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="prose prose-gray max-w-none">
          <h2>Nature of Service</h2>
          <p>
            ESGTracker provides automated ESG (Environmental, Social, and
            Governance) report generation using artificial intelligence. Our
            reports are designed to help businesses understand their ESG posture
            and identify areas for improvement.
          </p>

          <h2>Not Professional Advice</h2>
          <p>
            <strong>
              The content generated by ESGTracker does not constitute and should
              not be construed as:
            </strong>
          </p>
          <ul>
            <li>Legal advice or legal representation</li>
            <li>Financial advice or investment recommendations</li>
            <li>Tax advice or tax planning guidance</li>
            <li>Certified audit or assurance services</li>
            <li>Official regulatory compliance certification</li>
            <li>Environmental impact assessments</li>
            <li>Professional consulting services</li>
          </ul>

          <h2>AI Limitations</h2>
          <p>Our AI-powered reports:</p>
          <ul>
            <li>
              Are based on the information you provide and may not capture all
              relevant factors
            </li>
            <li>
              Use industry benchmarks and general best practices that may not
              apply to your specific situation
            </li>
            <li>May contain errors, inaccuracies, or outdated information</li>
            <li>
              Should be verified by qualified professionals before use in
              official contexts
            </li>
            <li>
              Are not a substitute for professional judgment and expertise
            </li>
          </ul>

          <h2>Regulatory Compliance</h2>
          <p>
            ESGTracker reports are <strong>not</strong> designed to satisfy the
            requirements of:
          </p>
          <ul>
            <li>
              EU Corporate Sustainability Reporting Directive (CSRD) official
              submissions
            </li>
            <li>SEC climate disclosure requirements</li>
            <li>GRI Standards certified reporting</li>
            <li>SASB Standards certified reporting</li>
            <li>CDP questionnaire responses</li>
            <li>B Corp certification assessments</li>
            <li>Any other regulatory or certification requirements</li>
          </ul>
          <p>
            If you need to meet specific regulatory requirements, you must work
            with qualified professionals, certified auditors, and legal counsel.
          </p>

          <h2>No Guarantee of Accuracy</h2>
          <p>
            While we strive to provide accurate and helpful information, we make
            no warranties or representations regarding the accuracy,
            completeness, reliability, or suitability of the reports for any
            particular purpose. The use of our Service and reliance on any
            generated content is at your own risk.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by applicable law, ESGTracker, its
            affiliates, officers, directors, employees, and agents shall not be
            liable for any:
          </p>
          <ul>
            <li>
              Direct, indirect, incidental, special, consequential, or punitive
              damages
            </li>
            <li>Loss of profits, revenue, data, or business opportunities</li>
            <li>Regulatory fines or penalties</li>
            <li>Reputational damage</li>
            <li>
              Any other losses arising from your use of or reliance on our
              Service
            </li>
          </ul>

          <h2>Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless ESGTracker from any claims,
            damages, losses, liabilities, and expenses arising from your use of
            the Service or your violation of these terms.
          </p>

          <h2>Recommendation</h2>
          <p>
            We strongly recommend that you:
          </p>
          <ul>
            <li>
              Consult with qualified ESG consultants, legal advisors, and
              auditors for official reporting
            </li>
            <li>
              Verify all data and recommendations before implementing changes
            </li>
            <li>
              Use ESGTracker reports as a starting point for further
              professional analysis
            </li>
            <li>
              Stay informed about applicable regulations in your jurisdiction
            </li>
          </ul>

          <h2>Contact</h2>
          <p>
            If you have questions about this disclaimer, please contact us at:
            <br />
            Email: legal@esgtracker.io
          </p>
        </div>
      </div>
    </div>
  );
}
